<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0">
    </PackageReference>
    <PackageReference Include="MSTest.TestAdapter" Version="3.1.1">
    </PackageReference>
    <PackageReference Include="MSTest.TestFramework" Version="3.1.1">
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\PlatformIndependentNuGetPackages\SunamoCl\SunamoCl.csproj" />
    <ProjectReference Include="..\..\..\PlatformIndependentNuGetPackages\SunamoCmd\SunamoCmd.csproj" />
    <ProjectReference Include="..\..\..\PlatformIndependentNuGetPackages\SunamoPercentCalculator\SunamoPercentCalculator.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
    <NoWarn>CA1822;CS1573;CS1572;CS1570;CA1866;CA2249</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
    <NoWarn>CA1822;CS1573;CS1572;CS1570;CA1866;CA2249</NoWarn>
  </PropertyGroup>
</Project>