<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SunamoCollectionsGeneric" Version="24.2.6.2" />
    <PackageReference Include="SunamoEnums" Version="24.2.6.2" />
    <PackageReference Include="SunamoExceptions" Version="24.2.6.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.6.6"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\sunamoWithoutLocalDep\SunamoStringReplace\SunamoStringReplace.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
</Project>