<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SunamoPlatformUwpInterop" Version="24.1.10.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\PlatformIndependentNuGetPackages\SunamoDebugIO\SunamoDebugIO.csproj" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;SunamoDebugIO.Tests;SunamoDebugIO.Tests.csproj</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC;SunamoDebugIO.Tests;SunamoDebugIO.Tests.csproj</DefineConstants>
  </PropertyGroup>
</Project>