<?xml version='1.0' encoding='utf-8'?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
   <TargetFramework>net6.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\sunamoWithoutDep\SunamoTray\SunamoTray.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamo\desktop\desktop.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamo\forms\forms.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamo\shared\shared.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamo\sunamo\sunamo.csproj"></ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="SunamoTray.Tests.ico"></Resource>
  </ItemGroup>
</Project>