<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Nunit\Dog.cs"></Compile>
    <Compile Remove="Nunit\JsonParserTests.cs"></Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="Data\Dog.cs"></None>
    <None Include="Nunit\JsonParserTests.cs"></None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0"></PackageReference>
    <PackageReference Include="xunit" Version="2.4.0"></PackageReference>
    <PackageReference Include="xunit.extensibility.core" Version="2.4.1"></PackageReference>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0"></PackageReference>
    <PackageReference Include="coverlet.collector" Version="1.2.0"></PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\sunamo.Tests\TestValues\TestValues.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamoWithoutDep\SunamoJson\SunamoJson.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamo\shared\shared.csproj"></ProjectReference>
    <ProjectReference Include="..\..\..\sunamo\sunamo\sunamo.csproj"></ProjectReference>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants>$(DefineConstants);ASYNC</DefineConstants>
  </PropertyGroup>
</Project>